/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h> /* for ptrdiff_t below */

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */




/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef __SIZE_TYPE__ GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


// 1. generate random seed and return uint64 as random value
extern char* GenRandomSign();

// 2. sign_pass: check if input inRandomSign matches inSignAck
extern GoUint8 sign_pass(char* inRandomSign, char* inSignAck);

// 4. 查看原始证书
// 输入: lic_path, sign
// 输出: code, message, checksign, data
extern char* InfoOrigin(char* lic_path, char* sign);

// 5. 导入证书
// 输入: lic_path, uuid, sign
// 输出: code, message, checksign, data
extern char* ImportLicense(char* lic_path, char* uuid, char* sign);

// 6. 查看已导入证书
// 输入: uuid, sign
// 输出: code, message, checksign, data
extern char* InfoAppled(char* uuid, char* sign);

// 5. 启动后台监测,更新已导入证书线程(已经实现单例)
// 输入: uuid, sign
// 输出: code, message, checksign, data
extern char* ElapsedThreadSingle(char* uuid, char* sign);

#ifdef __cplusplus
}
#endif
