echo "=====================yes========================="
    ./sshrpc.exe -ip ${Ip} -l "ls -lh /usr/bin/check_cpu_frequency.sh"
    ./sshrpc.exe -ip ${Ip} -l "ls -lh /usr/bin/check_docker_config.sh"
    ./sshrpc.exe -ip ${Ip} -l "ls -lh /usr/bin/clear_docker_images.sh"
    ./sshrpc.exe -ip ${Ip} -l "ls -lh /usr/bin/clear_docker_logs.sh"
    ./sshrpc.exe -ip ${Ip} -l "ls -lh /usr/bin/clear_system_logs.sh"
    ./sshrpc.exe -ip ${Ip} -l "ls -lh /usr/bin/deletelog.sh"
    ./sshrpc.exe -ip ${Ip} -l "ls -lh /usr/bin/load_libraT_utils.sh"
    ./sshrpc.exe -ip ${Ip} -l "ls -lh /usr/bin/open_the_gate.sh"
    ./sshrpc.exe -ip ${Ip} -l "ls -lh /usr/bin/reboot.sh"
    ./sshrpc.exe -ip ${Ip} -l "ls -lh /usr/bin/reload_sensor.sh"
    ./sshrpc.exe -ip ${Ip} -l "ls -lh /usr/bin/reload_sensor_template.sh"
    ./sshrpc.exe -ip ${Ip} -l "ls -lh /usr/bin/seal_the_gate.sh"
    ./sshrpc.exe -ip ${Ip} -l "ls -lh /usr/bin/synctime.sh"
    ./sshrpc.exe -ip ${Ip} -l "ls -lh /usr/bin/upload_ssh_key.sh"
    ./sshrpc.exe -ip ${Ip} -l "ls -lh /usr/bin/version_etcd_init.sh"
    ./sshrpc.exe -ip ${Ip} -l "ls -lh /usr/bin/vulcand_etcd_init.sh"
    ./sshrpc.exe -ip ${Ip} -l "ls -lh /usr/bin/weekly_clear.sh"